### ISSUE TITLE
Languages management problems

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#102]
qTranslate version 3.2.9.2

I've spotted some issues with the list of languages.

1) Deleting a manually added language won't deactivate it and it keeps listed in **Default Language / Order** and in dropdown list without any name or flag. I have to readd it, then deactivate it and finally delete it.

2) Editing **Language Code** in a pre-defined language will create a duplicate in the list that automatically substitutes the pre-activated with this new duplicate with new **Language Code**. This duplicate issue won't happen if editing **Language Code** of manually added languages.

**Comment by johnclause** [comment]
1) is fixed on 3.2.9.4
2) this is probably by design. If you change code of a manually added language, then there is no reason to keep the language with previous code, since if a new language wanted, then it can be added as new instead of replacing language code of existent language. Am I missing something?

**Comment by pedro-mendonca** [comment]
> 1) is fixed on 3.2.9.4

Great.

2) The correct behaviour is what's happening with the manually added languages of course, no duplicate is created..
This usually won't even be an issue because no one will want to change this, but I was messing around with the codes to invesigate the issue https://github.com/qTranslate-Team/qtranslate-x/issues/104 and found this possibility.
The incorrect behaviour that I've issued as bug is what's happening with predefined languages, the duplicate creation and all the confusion it creates because there is no easy way to spot the differences between the two listed languages if you just change the Language Code.

**Comment by johnclause** [comment]
pre-defined language cannot be deleted and code cannot be modified on them, that is why it creates a new language instead.

I added column 'Code' (3.2.9.5, the latest master) so that you one can distinct otherwise indistinctable items. I guess this is the best that can be done without a major re-design.

**Comment by pedro-mendonca** [comment]
Looks fine and usefull. :+1:

**Comment by pedro-mendonca** [comment]
Deleting added languages already disables them and remove them from the top order list.

**Comment by pedro-mendonca** [comment]
About de duplicate creation, I'm not sure if it should necessarly happen, because it works from the loaded database and not from the files. In the end this is not so important so I'm closing the issue as the main 1) problem is solved.

**Comment by johnclause** [comment]
>because it works from the loaded database
It now reads both and merge. This fixes the problem, when newly added pre-defined languages would not show up. Also it keeps database cleaner, since it stores only modified or added languages. The majority of people never modify any language and database stays free from unnecessary values. It also helps to speed up the load a little bit.
