### ISSUE TITLE
Translation of fields in WP General Settings: JetPack incompatibility

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#108]
When I update **Site Title** or **Tagline** fields that now appears highlighted and tabbed with language flags in the Settings > Settings panel, it's content is erased. I've checked the database and the fields *blogname* and *blogdescription* got cleaned.
I've tried inserting different and same text for different languages, the behaviour is the same.
The only ways to readd it are:
1) General Settings > editing Site Title and Tagline in Raw Mode with [:pt]Título[:en]Title[:] tags.
2) Appearance > Customize, and after inserting the single fields Site Title and Tagline it populates both fields again in the General Settings.

qTranslate-x v.3.2.9.5

**Comment by pedro-mendonca** [comment]
I've tested with LSB and Raw Mode.
In Raw Mode the options are working and are well parsed by qtranslate when the site is rendered in different languages.
The problem happens when these fields are saved in LSB mode, get totally cleaned.

**Comment by johnclause** [comment]
Do you have Jetpack connected? If so then, this is an old know issue: https://wordpress.org/support/topic/site-titletagline-disappear-on-general-settings-update, also listed here https://qtranslatexteam.wordpress.com/known-issues/

Since there is a simple workaround and this is not a frequent use piece, it has low priority for fixing. Besides, fixing is not easy in this case, but someday we will do this. Let us keep it open as a reminder, which we did not have yet in github for this issue.

**Comment by pedro-mendonca** [comment]
This is it, it is Jetpack conflict :+1: 
Thanks.

**Comment by johnclause** [comment]
Hi Pedro @pedro-mendonca: I tried to test this problem today and it looks like it is gone by now with all the latest. Could you confirm?

**Comment by pedro-mendonca** [comment]
Hi @johnclause 
Yes, I confirm it's working now :+1: 
Thanks :)

**Comment by johnclause** [comment]
I wish all problems would go away like that ... :smile:
