### ISSUE TITLE
qtranxf_convertURL() issue with default Language

### ISSUE THREAD

**Issue by fabiangarga** [qTranslate-Team/qtranslate-x#161]
Hi i think there is an issue with this function.

To reproduce this error you have to check the option "Hide URL language information for default language." on advanced settings.

If i use qtranxf_convertURL(URL, Default_Language) it will give me the url without the language code in the URL, but with this doesn't change to the default language if im already on other language.

For example if my default language is German, and im on the English version of the website, if i click on the German link it will stay on the english version.
If i disable to hide the URL of the default language, the url will be always returned with the language prefix, and will work.

Is there any way to fix this?

**Comment by johnclause** [comment]
This function, has additional argument `$showDefaultLanguage`, which when set to true will always encode URL with a language, otherwise it senses option "Hide URL language information for default language" to keep URL consistent with the currently chosen language.

If you need a URL to switch the language, set $showDefaultLanguage=true, if you need a URL to keep the current language, set it to false.

I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by fabiangarga** [comment]
I didn't know that.
Thanks a lot for the reply!

**Comment by HardLink** [comment]
I changed the parameter. problem still exists

`if(!function_exists('qtrans_convertURL')){ 
    function qtrans_convertURL($url='', $lang='', $forceadmin = false, $showDefaultLanguage = true){ 
        return qtranxf_convertURL($url, $lang, $forceadmin, $showDefaultLanguage); 
    }  `

I check a checkbox Hide URL Information for Default language
the default language is English.
the second language is Spanish.
the language change widget always contains a link: site.com/en/page/ this creates a 302 redirect.
I want the default language switch to have the form site,com/page/
how to do it?
otherwise I have a lot of redirects on the site
