### ISSUE TITLE
Can't translate custom Text fields

### ISSUE THREAD

**Issue by Guntiss** [qTranslate-Team/qtranslate-x#165]
I Have custom plugin that has Text editor input field, but LSB doesn't show up. If I manually insert translation using [:en] tags, It nicely translates in frontend.

Any quick fix to make translation buttons to show up on editor?

**Comment by johnclause** [comment]
Please, lookup errors in Java Console (Ctrl+Shift+J), it may give you an idea. Is it for all post.php or just some specific post type?

**Comment by Guntiss** [comment]
JS Console doesn't show any errors.
Basically plugin has this code 
`foreach ($rowim as $key=>$rowimages){ `
 `        wp_editor( $rowimages->description, 'im_description'.$rowimages->id , $settings);`

It outputs text fields for every row, but they don't have language switcher.

**Comment by johnclause** [comment]
Which page is it in, /wp-admin/post.php or what? There is a draft of [Integration Guide](https://qtranslatexteam.wordpress.com/integration/), which kind of explain how to do custom configuration under the latest beta version, which needs a little bit more work.

If it is on post.php, then older option "Custom Fields" may do what you need: https://qtranslatexteam.wordpress.com/faq/#HowToTranslateCustomFields.

**Comment by Guntiss** [comment]
Under
wp-admin/admin.php?page=portfolios_huge_it_portfolio&task=edit_cat&id=1

**Comment by johnclause** [comment]
Could you describe what exactly you tried which did not work?

Ok, wp-admin/admin.php does not have LSB by default. You have to use the latest version from [GitHub](https://github.com/qTranslate-Team/qtranslate-x) and put, for example, the following configuration in the field "Custom Configuration" on "Integration" tab:
`{
"admin-config":{
	"admin":{
		"pages":{"admin.php":"page=portfolios_huge_it_portfolio&task=edit_cat"},
		"forms":{
			"myform_id":{
				"fields":{
					"wp-editor-area":{"jquery":".wp-editor-area"}
				}
			}
		}
	},
}
}
`
I assume class "wp-editor-area" is set on your input fields the same way as it is done on post.php.
"myform_id" should be the "id" attribute of the form, if there is one. Otherwise, pick an "id" of any enclosing element. Is TinyMCE involved? If it is setup in a standard way, like it is done on post.php, then it should be taken into account automatically.

If you read [Integration Guide](https://qtranslatexteam.wordpress.com/integration/), you should have a general idea what I am trying to do here and you can tune the details if needed. If LSB do not show up, then the page does not follow WP standard and you will need to set "anchors". appropriately. You may wish to set "anchors" anyway to change the default placement of LSB.

This folder https://github.com/qTranslate-Team/qtranslate-x/tree/master/dev/i18n-config has a few examples of i18n-config.json files, which should help you to understand the syntax of configuration.

This makes you the first user of new integration capabilities :+1:  Do not get discouraged, please, help us to tune it all in a user friendly way.

**Comment by Guntiss** [comment]
Thank you so much! Your code works just flawless (except comma in the end causes json syntax error)

And issue because of php 5.2 shows up again
![error](https://cloud.githubusercontent.com/assets/9088411/7866172/56b0e696-0576-11e5-8a27-251264c6487a.PNG)

Only problem is that after saving data it doesn't show LSB anymore, but I guess it is easy fixable.

Anyway, thanks again for such a great development :+1:

**Comment by johnclause** [comment]
The latest update from [GitHub](https://github.com/qTranslate-Team/qtranslate-x) should work with 5.2. Cannot you ask the host to upgrade? It is almost 10 years old ;) Which country and/or host still run it?

**Comment by Guntiss** [comment]
nano.lv, Actually one of the most popular hosting companies in Latvia. It's probably pointless to ask them for software upgrade regards to my experience with their support. And I believe they are not the only one who still runs outdated software.

**Comment by johnclause** [comment]
Ok, it is just strange to run software 10 years old, if there were so many updates since.

Anyway, were you able to achieve what you need by now? Can we close this issue?

**Comment by Guntiss** [comment]
PHP 5.2.17 is actually only 5 years old :D
Yes, thanks for support everything works fine!
