### ISSUE TITLE
deprecated WP_Widget

### ISSUE THREAD

**Issue by faina09** [qTranslate-Team/qtranslate-x#202]
PHP Notice:  The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre> instead. 

  ..\wp-content\plugins\qtranslate-x\qtranslate_widget.php
	Line 32: 		$this->WP_Widget('qtranslate', __('qTranslate Language Chooser', 'qtranslate'), $widget_ops);

should be:
$this->__construct('qtranslate', __('qTranslate Language Chooser', 'qtranslate'), $widget_ops);

**Comment by rootion** [comment]
Can't use this plugin for the same reason.  The error message is truly annoying:

```
 Notice: The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre> instead. in \wp-includes\functions.php on line 3457
```

Using WP 4.3-RC2-33619 and QTranslate-X 3.4.3

**Comment by 72quadrat** [comment]
Same as @rootion the quick fix works

**Comment by johnclause** [comment]
This has been taken care of in https://github.com/qTranslate-Team/qtranslate-x/pull/230. WIll be released in 3.4.5.

**Comment by koen84** [comment]
Ergo, qTranslate-X 3.4.4 that's currently pushed through wordpress.org is NOT 100% compatible with wordpress 4.3 as is "claimed by author".  Above fix still solves issue though.

**Comment by johnclause** [comment]
Yes, sorry, a few imperfections have been discovered and fixed by now. Could you test the latest version from [GitHub](https://github.com/qTranslate-Team/qtranslate-x), or this pre-release https://github.com/qTranslate-Team/qtranslate-x/releases/tag/3.4.5, which is currently the same as the latest, and most likely will be published on WordPress? Please, let us know if you find any problems on your sites. Thanks a lot!
