### ISSUE TITLE
I can't put the language switcher in the menu (with Wordpress)

### ISSUE THREAD

**Issue by luiscastellanos** [qTranslate-Team/qtranslate-x#212]
Hi.
I'm using the qtranslate-x plugin, and it works fine with the posts and pages. But I tried to insert the language switcher in the menu, but I can't make it work.
Can somebody please help me and tell me how to do it?
Thanks...
The page is: http://www.senainca.com.ve
![captura qtranslator](https://cloud.githubusercontent.com/assets/13752037/9204481/5bcc145c-4027-11e5-953a-4e7c451be896.png)

**Comment by luiscastellanos** [comment]
(I click on "Add ti menu" and nothing happens)

**Comment by Grafcom** [comment]
@luiscastellanos 
can you try it when you delete first some menu items? See if that makes a difference.
What theme do you use?

**Comment by luiscastellanos** [comment]
Hi Grafcom. I deleted the entire menu and tried to make a new one, but I think that the theme (Traffica)doesn't support the plugin, cause I couldn't even add a link nor the language switcher. I think I'll have to change the theme...
Thanks...

**Comment by Grafcom** [comment]
@luiscastellanos
Settings - Languages - Integration -- Compatibility Functions checked?

**Comment by Grafcom** [comment]
is this the theme?
https://wordpress.org/themes/traffica/
I can test on my test server if you like

**Comment by luiscastellanos** [comment]
That's the theme...

**Comment by Grafcom** [comment]
OK, on my test server it works as it should (?)

**Comment by Wagon17** [comment]
@luiscastellanos and @Grafcom i was having some similar issues. I used a fixed widget plugin and i could make it appear in my menu yet as i select the dropdown feature, the dropdown box has two dropdown arrows and the two languages are repeated. so it shows four languages to choose from. the language names are repeated once but i do wish to rectify the mistake. can you help?

**Comment by johnclause** [comment]
This is from like a year ago, many things are changed since.

@Wagon17: description of your problem does not really match the original one. Which versions of WP and qtx do you use? Does it work correctly if you switch the theme to one of the standard one, like "Twenty Sixteen"? If it does, then contact the theme asking what is the difference. If you wish us to figure it out, then send a request via https://qtranslatexteam.wordpress.com/contact-us/ with detailed descripton of your particular setup.

I am closing this issue, as outdated and apparently resolved. We can still write into closed issue or can reopen it if needed.
