### ISSUE TITLE
Duplicated content inside Wordpress using Qtranslate-x

### ISSUE THREAD

**Issue by arthursiqueira** [qTranslate-Team/qtranslate-x#253]
Every time I use the qTranslate-X I have the same problem , the contents inside the wordpress duplicates a lot of times , making it impossible to use the plugin .

ex: 

![example_qtranslatebug](https://cloud.githubusercontent.com/assets/14221206/9794312/c62d43ec-57c0-11e5-9879-0556f9dbd9c9.jpg)

please, anyone knows how to fix this bug??

thx 

Att, Arthur Siqueira

**Comment by johnclause** [comment]
Hi Arthur, it is probably some incompatibility or misuse. It is hard to tell without step-by-step instructions to reproduce the problem. If problem is still there, put a reproducing instruction here. I will close it for now, assuming that problem is resolved, we can still write into closed issue or can reopen it if needed.

**Comment by arthursiqueira** [comment]
Im using the Avada Theme with Fusion Builder, there is some incompatibility already known ?

**Comment by Grafcom** [comment]
@arthursiqueira 
read this https://qtranslatexteam.wordpress.com/known-issues/ and look here: https://qtranslatexteam.wordpress.com/incompatible/

**Comment by johnclause** [comment]
Yes, your theme must need an integration: https://qtranslatexteam.wordpress.com/integration/ If you wish us to integrate it for you, submit a request for a paid job via https://qtranslatexteam.wordpress.com/contact-us/. Thank you.
