### ISSUE TITLE
qtranslate-x and cornerstone on x-theme

### ISSUE THREAD

**Issue by danielasciarma** [qTranslate-Team/qtranslate-x#314]
Hi,
I want know if  is qtranslate-x compatible with pages builded on cornerstone and, if it's possible, how can I do to build a, for example, spanish page, equal in structure but different in language from an italian page.

Thank you very much

**Comment by johnclause** [comment]
Hi @danielasciarma: I think that relatively few people know what 'cornerstone' is. I do not have it. You will probably not get much of response here. However, qtx is virtually compatible with anything, but an [integration](https://qtranslatexteam.wordpress.com/integration/) may be needed. Let us know how did it go with your project. Thanks.

I am closing it for now, since I do not know what else I can do here, we can still write into closed issue and can re-open if needed.
