### ISSUE TITLE
Adding language switch menu

### ISSUE THREAD

**Issue by juan-san** [qTranslate-Team/qtranslate-x#388]
Hi,

I installed the qtranslate-x plugin and I am having problems having the language switcher appear in the menu or anywhere on the page.

I am using a theme called Bionick and when I asked their support they said I could get it to work adding code. Would you be able to provide me with some assistance on making the switcher appear?

I seem to be able to create content in all different languages everywhere but having the language switcher appear is being a problem.

I appreciate any guidance or help I can receive.

Thank you,

**Comment by johnclause** [comment]
Very strange problem. Did they explain what is wrong? If the theme follows WP rules, menu should work. They probably customized it completely without applying standard WP filters, particularly 'wp_get_nav_menu_items'. I would say they must provide you with a way to inject custom items into their menu through some filters and then you could use those to add items you need, following the code in function 'qtranxf_wp_get_nav_menu_items'.

Alternatively, you may try to build custom language menu with custom menu items: https://qtranslatexteam.wordpress.com/faq/#CustomMenuLang. Actually, it may not work either, if they did not apply the standard WP filter.

Alternatively, you may use widget, instead of menu: https://qtranslatexteam.wordpress.com/faq/#LanguageSwitchingMethods

If you need more help with this, submit a request for paid job: https://qtranslatexteam.wordpress.com/contact-us/
