### ISSUE TITLE
Ubermenu not translating

### ISSUE THREAD

**Issue by backpacksbridges** [qTranslate-Team/qtranslate-x#409]
Hello,
I am using X Theme to develop my site. I have no knowledge of code. in short, I am using an ubermenu, but it no longer changes the language of menu items when changing language. Help much appreciated.

**Comment by johnclause** [comment]
Versions? Updates? https://qtranslatexteam.wordpress.com/2016/04/23/release-notes-3-4-6-5/

**Comment by backpacksbridges** [comment]
Sorry about that, in the meantime I fixed that problem, and then realised that qtranslate isn't compatible with X Theme's Cornerstone. Any chance it will be integrated? In the meantime, any help on using cornerstone and qtranslate together?

**Comment by johnclause** [comment]
There is always a chance, somebody will follow the [Integration Guide](https://qtranslatexteam.wordpress.com/integration/) for that theme, or you may ask the theme to integrate, or you may do it yourselves, or you may hire a PHP developer, [including us](https://qtranslatexteam.wordpress.com/contact-us/).

Since you found a fix, it seems that this issue can be closed as an issue, can it be? We may keep writing into closed issue or may re-open it if needed. Thanks a lot!
