### ISSUE TITLE
Add/remove content hooks dynamically

### ISSUE THREAD

**Issue by funkjedi** [qTranslate-Team/qtranslate-x#58]
When custom fields are added/removed from a post I'm looking for a way to be able to add/remove the content hooks from the frontend (since the page has already loaded).

One approach would be to expose the `qTranslateX` instance on the `window` object. That would allow calling the `addContentHook*` methods.

```js
jQuery(document).ready(function($){ 
    window.qtx = new qTranslateX(qTranslateConfig.js);
});
```

**Comment by johnclause** [comment]
Ok, Tim, I have put that in, will be out in next release.

I was also thinking about configuration attribute like { 'js' => 'path_to_custom.js'} to load custom script if needed. When inside an integration plugin, it is probably not important, because one can add its own script easily, but when it goes to a simple configuration option or file without plugin implemented, it may be necessary. Do you think it would make sense and be helpful to someone?

**Comment by johnclause** [comment]
Hi Tim, I was worried that 'qtx' name is too short, which increases chances of a conflict with somebody. Then I thought, that we already have global variable 'qTranslateConfig' in any case, so I can store pointer to qTranslateX object in qTranslateConfig.qtx variable and that will be safer, while makes no difference to you? What do you think?

**Comment by funkjedi** [comment]
Good thinking `qTranslateConfig.qtx` is a great place for it.

Having a filter on the return value of `qtranxf_select_admin_js()` would be great. When `SCRIPT_DEBUG` is turned on I can just deregister and then register my own `qtranslate-admin-edit` script. However since the file is manually output using `readfile()` when `SCRIPT_DEBUG` is turned off this really isn't an option.

**Comment by johnclause** [comment]
Sorry for the delay in response, Tim. I was going to tell you that `qtranxf_select_admin_js` may be gone at all in the future design. I'll talk on the details of it later, maybe under different topic.
