### ISSUE TITLE
Front page encoding doesn't work

### ISSUE THREAD

**Issue by KamilKopaczyk** [qTranslate-Team/qtranslate-x#77]
Hello,

i'm using 3.2.7 version.

Encoding [:] or  does not work on front page.
I tried:
[:en]English[:de]Deutsch
[:en]English[:de]Deutsch[:]
[:en]English[:][:de]Deutsch[:]

and the same combination for  syntax.

Any ideas?

**Comment by johnclause** [comment]
Does it work under standard theme like "Twenty Fifteen" and -X the only plugin? Did it ever work before, under which version, plugin, theme? Please, give enough information to reproduce the case, or give us admin access to a test-copy of your site.

**Comment by KamilKopaczyk** [comment]
I updated from 3.2.1 becuase of this issue.

I just reproduced it on a fresh copy:
1) Setup wordpress (i was using vagrantpress)
2) Install qtranslate-x plugin
3) Create front-page.php in twentyfifteen category
4) Add encoded content (in my example [:en]English[:de]Deutsch)
5) Visit main page

**Comment by johnclause** [comment]
#1, I am not familiar with vagrantpress.
#3. not clear what to do
#4. You should not be using  '[:en]English[:de]Deutsch', it should show Language Switching Buttons, which you use to switch language to edit.

It seems like you know how PHP works? Can you figure out what is wrong and let us know what need to be done?

**Comment by KamilKopaczyk** [comment]
I edited my last comment. In 3. it was meant to be 'directory'.

The point is: it works well in posts, but it doesn't work in pages like index.php.

Could you point me where should i look for the code responsible for post content translation? I could try to work something out.

**Comment by johnclause** [comment]
First, do you see Language Switching Buttons, like on screenshot shown here https://wordpress.org/plugins/qtranslate-x/stats/? Are there error messages in Java Console? You should not be using tags '[:en]' manually.

There is no single place I can point you to, it depends on many circumstances how it is in use. Find the place where the text in trouble goes out, see where it comes from, and which filters it is being passed through before going out.

>Create front-page.php

What code did you put there?

When any field has multilingual information encoded, it is normally enough to pass it through translation function `__()` in order to extract the active language.

When you say "does not work on front page", do you mean that multilingual fields are shown untranslated, or not shown at all, or what exactly does not work?

**Comment by KamilKopaczyk** [comment]
I'm not in the context of a post. It's in a template, which for example contains foreach loop, that displays 10 recent posts. 
What i'm trying to do is to insert some translated content outside of this loop, for example right after the menu.
Easiest way to do/test it, is to open index.php (located in theme root directory or accessible from wp-admin Appearance -> Editor -> select index.php) and try to translate something in there.

**Comment by johnclause** [comment]
So, you are doing custom modifications of the code, otherwise all works fine? Is that right?

>translated content
where it is taken from?

>try to translate something in there
explain what this means

Otherwise, my guess would be to use  function `__()`.

**Comment by johnclause** [comment]
Hi Kamil, is this issue resolved?

**Comment by KamilKopaczyk** [comment]
Yes, thank you.
