### ISSUE TITLE
Temporarily disable get_terms translation?

### ISSUE THREAD

**Issue by tyteen4a03** [qTranslate-Team/qtranslate-x#86]
I have a function in the admin panel that relies on `get_terms` to gather all translated term names, using `mqtranslate_term_name` option to match up the translation with the term. In mqTranslate `get_terms` always returned the term in the default language (in my case, Trad. Chinese) but in qTranslate X translates the terms according to the admin panel language so I get English terms when I use an English interface. 

I tried `remove_filter` but it didn't have any effect. How do I temporarily disable the `get_terms` hook, or is there a better way to do this?

**Comment by johnclause** [comment]
On admin side, it is hooked by the line `add_filter('get_terms', 'qtranxf_useAdminTermLibJoin', 5, 3);`. 

You probably removed it before it was added. It gets added at the end of function `qtranxf_init_language` with the line `require_once(dirname(__FILE__).'/admin/admin_utils.php');`. I believe, it can be removed in action `do_action('qtranslate_init_language',$url_info);`, which is executed at the very end of `qtranxf_init_language`.

Be careful to remove only on your specific page in trouble, otherwise many things may get broken.
